config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  scope module: :public do
    root to: "items#top"
    get '/about' => 'homes#about'

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :confirm, :complete, :create, :index, :show] do
      collection do
        post "confirm"
        get "complete"
      end
    end
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "/customers/mypage" => "customers#show"
    get "/customers/information/edit" => "customers#edit"
    patch "/customers/information" => "customers#update"
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdrawal" => "customers#withdrawal"
    resources :items, only: [:index, :show]
    resources :homes, only: [:top, :about]
  end



  namespace :admin do
    root to: "homes#top"
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update] do
      collection do
        get "search"
      end
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update] do
      collection do
        get "search"
      end
    end
    resources :homes, only: [:top]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :orders, through: :order_details, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :customers, through: :cart_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre

  has_one_attached :image

  scope :search_by_keyword, -> (keyword) { where("name LIKE ?", "%#{keyword}%") }

  def get_image#画像取得メソッド(画像選択していない場合no_imageが表示される)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [300, 400]).processed
  end
  
  def tax_price
    price*1.1
  end

  def tax_price
    price*1.1
  end

validates :image, presence: true
validates :name, presence: true
validates :introduction , presence: true
validates :genre_id, presence: true
validates :price , presence: true

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if  @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end
  
  def search
   @itemss = Item.search_by_keyword(params[:keyword])
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active, :image)
  end

end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-8"><h2 class="ml-5 mt-4">商品編集</h2></div>
    <div class="col-3"></div>
  </div>

  <div class="row justify-content-center mt-4">
    <%= render 'layouts/errors', obj: @item %>
      <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
    <div class="form-group row my-3">
      <div class="col-3"><%= f.label "商品画像"%></div>
      <div class="col-9"><%= f.file_field :image, accept: "image/*",class:"ml-4" %></div>
    </div>

    <div class="form-group row my-3">
      <div class="col-3"><%= f.label "商 品 名" %></div>
      <div class="col-9"><%= f.text_field :name, placeholder: "商品名", class:"ml-4 form-control" %></div>
    </div>

    <div class="form-group row my-3">
      <div class="col-3"><%= f.label "商品説明" %></div>
      <div class="col-9"><%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class:"ml-4 form-control h-100" %></div>
    </div>

    <div class="form-group row my-3">
      <div class="col-3"><%= f.label "ジャンル" %></div>
      <div class="col-9"><%= f.collection_select :genre_id, Genre.all, :id,:name,{prompt: "--選択してください--"} ,class:"ml-4 form-control"%></div>
    </div>

    <div class="form-group row mb-3">
      <div class="col-3"><%= f.label "税抜価格" %></div>
      <div class="col-8"><%= f.text_field :price, placeholder: "1000",class:"ml-4 form-control"%></div>
      <div class="col-1 align-bottom">円</div>
    </div>

    <div class="form-group row mb-4">
      <div class="col-4"><%= f.label "販売ステータス" %></div>
      <div class="col-8"><%= f.radio_button :is_active, true,class:"ml-4" %>販売中
                        <%= f.radio_button :is_active, false,class:"ml-4" %>販売停止中</div>
    </div>

    <div class="form-group text-center">
      <%= f.submit "変更を保存",class:"btn btn-success px-4 py-2",style:"font-size:1.2em;"%>
    </div>
      <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row my-4">
    <div class="col-11">
    <h2 class-"font-weight-bold">商品一覧</h2>
    </div>
    <div class="col-1">
    <%= link_to "+",new_admin_item_path,class: "btn btn-secondary rounded-circle p-0 mt-2",style: "font-size:20px;width:2rem;height:2rem;" %><!--商品新規登録ページへのボタン-->
    </div>
  </div>

  <div class="row">
    <table class='table table-hover'>
      <thead class="thead-light">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル </th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody class="table-borderless">
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item.id) %></td>
          <td><%= item.price.floor.to_s(:delimited) %></td>
          <td><%= item.genre.name %></td>
          <td class="font-weight-bold">
            <% if item.is_active == true %>
                <p class="text-success">販売中</p>
              <% else %>
                <p class="text-muted">販売停止中</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-8"><h2 class="ml-5 mt-4">商品新規登録</h2></div>
    <div class="col-3"></div>
  </div>

  <div class="row justify-content-center mt-3">
    <%= render 'layouts/errors', obj: @item %>
      <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
    <div class="form-group row my-3">
      <div class="col-3"><%= f.label "商品画像"%></div>
      <div class="col-9"><%= f.file_field :image, accept: "image/*",class:"ml-4" %></div>
    </div>

    <div class="form-group row my-3">
      <div class="col-3"><%= f.label "商 品 名" %></div>
      <div class="col-9"><%= f.text_field :name, placeholder: "商品名", class:"ml-4 form-control" %></div>
    </div>

    <div class="form-group row my-3">
      <div class="col-3"><%= f.label "商品説明" %></div>
      <div class="col-9"><%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class:"ml-4 form-control h-100" %></div>
    </div>

    <div class="form-group row my-3">
      <div class="col-3"><%= f.label "ジャンル" %></div>
      <div class="col-9"><%= f.collection_select :genre_id, Genre.all, :id,:name,{prompt: "--選択してください--"} ,class:"ml-4 form-control"%></div>
    </div>

    <div class="form-group row mb-3">
      <div class="col-3"><%= f.label "税抜価格" %></div>
      <div class="col-8"><%= f.text_field :price, placeholder: "1000",class:"ml-4 form-control"%></div>
      <div class="col-1 align-bottom">円</div>
    </div>

    <div class="form-group row mb-4">
      <div class="col-4"><%= f.label "販売ステータス" %></div>
      <div class="col-8"><%= f.radio_button :is_active, true,class:"ml-4" %>販売中
                        <%= f.radio_button :is_active, false,class:"ml-4" %>販売停止中</div>
    </div>

    <div class="form-group text-center">
      <%= f.submit "新規登録",class:"btn btn-success px-4 py-2",style:"font-size:1.2em;"%>
    </div>
      <% end %>
  </div>
</div>

app/views/admin/items/search.html.erb
  <div class="col-md-8">
   <h1>検索結果</h1>

  <% if @itemss.present? %>
  <ul>
    <% @itemss.each do |item| %>
      <li><%= link_to item.name, item_path(item) %></li>
    <% end %>
  </ul>
<% else %>
  <p>該当する商品がありませんでした。</p>
<% end %>
  </div>

app/views/admin/items/show.html.erb
<div class="container mt-5">
<h2>商品詳細</h2>

  <div class="row">
    <div class="col-5 mt-3">
      <%= image_tag @item.get_image %>
    </div>

    <div class="col-7 mt-3">
      <div style="pb-5">
        <p style="font-size:1.1em;">商 品 名 <span class="ml-5" style="font-size:1.2em;"><%= @item.name%></span></p>
      </div>

      <div style="pb-5">
        <p style="font-size:1.1em;">商品説明<span class="ml-5" style="font-size:1.2em;"><%= @item.introduction %></span></p>
      </div>

      <div style="pb-5">
        <p style="font-size:1.1em;">ジャンル<span class="ml-5" style="font-size:1.2em;"><%= @item.genre.name %></span></p>
      </div>

      <div style="pb-5">
        <p style="font-size:1.1em;">税込価格<br>(税抜価格)<span class="ml-5" style="font-size:1.2em;"><%= (@item.price*1.1).floor.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</span></p>
      </div>

      <div style="pb-5">
        <p style="font-size:1.0em;">販売ステータス
          <span class="ml-2 font-weight-bold"><% if @item.is_active == true %>
              <span class="text-success" style="font-size:1.2em;">販売中</span>
            <% else %>
              <span class="text-muted" style="font-size:1.2em;">販売停止中</span>
          <% end %>
          </span>
        </p>
      </div>

      <div class="ml-5 mt-5">
      <%= link_to "編集する", edit_admin_item_path(@item),class:"btn btn-success px-4 py-2",style:"font-size:1.2em;" %>
      </div>

    </div>
  </div>
</div>