config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  scope module: :public do
    root to: "items#top"
    get '/about' => 'homes#about'

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :confirm, :complete, :create, :index, :show] do
      collection do
        post "confirm"
        get "complete"
      end
    end
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "/customers/mypage" => "customers#show"
    get "/customers/information/edit" => "customers#edit"
    patch "/customers/information" => "customers#update"
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdrawal" => "customers#withdrawal"
    resources :items, only: [:index, :show]
    resources :homes, only: [:top, :about]
  end



  namespace :admin do
    root to: "homes#top"
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update] do
      collection do
        get "search"
      end
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update] do
      collection do
        get "search"
      end
    end
    resources :homes, only: [:top]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :items, through: :cart_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  VALID_KANA_REGEX = /\A[ァ-ヶー－]+\z/
  validates :last_name_kana, presence: true, format: { with: VALID_KANA_REGEX }
  validates :first_name_kana, presence: true, format: { with: VALID_KANA_REGEX }
  VALID_POSTAL_CODE_REGEX = /\A\d{3}[-]?\d{4}\z/
  validates :post_code, presence: true, format: { with: VALID_POSTAL_CODE_REGEX }
  validates :address, presence: true
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  validates :phone_number, presence: true, format: { with: VALID_PHONE_REGEX }, uniqueness: true
  validates :is_deleted, inclusion: { in: [true, false] }

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :set_q, only: [:index, :search]
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  def search
    @results = @q.result.page(params[:page]).per(10)
  end

  private

  def set_q
    @q = Customer.ransack(params[:q])
  end

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :post_code, :address, :phone_number, :is_deleted)
  end
end

app/views/admin/customers/edit.html.erb
<div class="container my-5">
  <div class="row no-gutters">
      <div class="col-lg-12">
        <h3><strong><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</strong></h3>
      <%= render 'layouts/errors', obj: @customer %>
      <%= form_with model: @customer, url: admin_customer_path, method: :patch, local: true do |f| %>
        <div>
          <div class="col-xs-12">
            <%= f.label "氏名", class: "col-sm-3", style: "margin: 10px;" %>
            <%= f.text_field :last_name, class: "col-sm-3", style: "margin: 10px;", placeholder: "令和" %>
            <%= f.text_field :first_name, class: "col-sm-3", style: "margin: 10px;", placeholder: "道子" %>
          </div>
          <div class="col-xs-12">
            <%= f.label "フリガナ", class: "col-sm-3", style: "margin: 10px;" %>
            <%= f.text_field :last_name_kana, class: "col-sm-3", style: "margin: 10px;", placeholder: "レイワ" %>
            <%= f.text_field :first_name_kana, class: "col-sm-3", style: "margin: 10px;", placeholder: "ミチコ" %>
          </div>
          <div class="col-xs-12">
            <%= f.label "メールアドレス", class: "col-sm-3", style: "margin: 10px;" %>
            <%= f.email_field :email, autocomplete: "email", class: "col-sm-6", style: "margin: 10px;", placeholder: "example@example.com" %>
          </div>
          <div class="col-xs-12">
            <%= f.label "郵便番号(ハイフンなし)", class: "col-sm-3", style: "margin: 10px;" %>
            <%= f.text_field :post_code, class: "col-sm-2", style: "margin: 10px;", placeholder: "0000000" %>
          </div>
          <div class="col-xs-12">
            <%= f.label "住所", class: "col-sm-3", style: "margin: 10px;" %>
            <%= f.text_field :address, class: "col-sm-8", style: "margin: 10px;", placeholder: "東京都渋谷区代々木神園町0-0" %>
          </div>
          <div class="col-xs-12">
            <%= f.label "電話番号(ハイフンなし)", class: "col-sm-3", style: "margin: 10px;" %>
            <%= f.text_field :phone_number, class: "col-sm-3", style: "margin: 10px;", placeholder: "00000000000" %>
          </div>
          <div class="col-xs-12">
            <%= f.label "会員ステータス", class: "col-sm-3", style: "margin: 10px;" %>
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, "有効" %>
            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted, "退会" %></p>
          </div>
        </div>
  
        <div>
          <p>
            <%= f.submit "編集内容を保存", class: "btn btn-success col-sm-3", style: "margin: 10px;" %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container my-5">
  <div class="row no-gutters">
    <div class="col-lg-12 col-xs-offset-1">
      <h2>会員一覧</h2>
      <table class="table table-bordered">
        <thead style="background-color: #f0f8ff;">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td style="background-color: #f5f5f5;"><%= customer.id %></td>
              <td class="text-dark">
              <%= link_to admin_customer_path(customer.id) do %>
                <div class="text-dark"><%= customer.full_name %></div>
              <% end %>
              </td>
              <td><%= customer.email %></td>
              <td><%= customer.is_deleted ? '退会' : '有効' %></td>
            </tr>
            <% end %>
            <%= paginate @customers %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/search.html.erb
<div class="container my-5">
  <div class="row no-gutters">
    <div class="col-lg-12 col-xs-offset-1">
      <h2>検索結果一覧</h2>
      <%= search_form_for @q, url: search_admin_customers_path do |f| %>
        <%= f.search_field :last_name_or_first_name_or_last_name_kana_or_first_name_kana_cont, placeholder: "姓 or 名 or セイ or メイ" %>
        <%= f.submit '🔍', class: "btn-sm btn-outline-secondary" %>
      <% end %>
      <table class="table table-bordered">
        <thead style="background-color: #f0f8ff;">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @results.each do |customer| %>
            <tr>
              <td style="background-color: #f5f5f5;"><%= customer.id %></td>
              <td>
              <%= link_to admin_customer_path(customer.id) do %>
                <div class="text-dark"><%= customer.full_name %></div>
              <% end %>
              </td>
              <td><%= customer.email %></td>
              <td><%= customer.is_deleted ? '退会' : '有効' %></td>
            </tr>
            <% end %>
        </tbody>
      </table>
      <%= paginate @results %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 md-5 offset-md-1">
      <%= flash[:notice] %>
      <h3 style="margin-top: 50px;"><strong>会員詳細</strong></h3>
      <table class="table table-bordered">
        <div class="col" style="margin-top: 50px;">
          <p>
            <strong class="h4"><%= @customer.full_name %>さんの会員情報詳細</strong>
            <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success", style: "margin-left: 635px;" %>
          </p>
          <div class='col-md-10'>
            <thead>
              <tr class="table">
                  <th style="background-color:#f0f8ff;">会員ID</th>
                <td><%= @customer.id %></td>
              </tr>

              <tr class="table">
                <th style="background-color:#f0f8ff;">氏名</th>
                <td><%= @customer.full_name %></td>
              </tr>

              <tr class="table">
                <th style="background-color:#f0f8ff;">カナ</th>
                <td><%= @customer.full_name_kana %></td>
              </tr>

              <tr class="table">
                <th style="background-color:#f0f8ff;">郵便番号</th>
                <td><%= @customer.post_code %></td>
              </tr>

              <tr class="table">
                <th style="background-color:#f0f8ff;">住所</th>
                <td><%= @customer.address %></td>
              </tr>

              <tr class="table">
                <th style="background-color:#f0f8ff;">電話番号</th>
                <td><%= @customer.phone_number %></td>
              </tr>

              <tr class="table">
                <th style="background-color:#f0f8ff;">メールアドレス</th>
                <td><%= @customer.email%></td>
              </tr>

              <tr class="table">
                <th style="background-color:#f0f8ff;">会員ステータス</th>
                <td><%= @customer.is_deleted ? '退会' : '有効' %></td>
              </tr>
            <thead>
          </div>
        </div>
      </table>
      <p>
      <div class="row no-gutters">
        <%#= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %>
        <%= link_to "注文履歴一覧を見る(仮)", admin_order_path(@customer), class: "btn btn-primary" %>
      </div>
      </p>
    </div>
  </div>
</div>