config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  scope module: :public do
    root to: "items#top"
    get '/about' => 'homes#about'

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :confirm, :complete, :create, :index, :show] do
      collection do
        post "confirm"
        get "complete"
      end
    end
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "/customers/mypage" => "customers#show"
    get "/customers/information/edit" => "customers#edit"
    patch "/customers/information" => "customers#update"
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdrawal" => "customers#withdrawal"
    resources :items, only: [:index, :show]
    resources :homes, only: [:top, :about]
  end



  namespace :admin do
    root to: "homes#top"
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update] do
      collection do
        get "search"
      end
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update] do
      collection do
        get "search"
      end
    end
    resources :homes, only: [:top]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :items, through: :order_details, dependent: :destroy
  has_many :order_details, dependent: :destroy

  enum order_status: {
     "入金待ち":0, "入金確認":1, "製作中":2, "発送準備中":3, "発送済み":4
  }
  enum pay_type: { credit_card: 0, transfer: 1 }

private
  def order_params
    params.require(:order_detail).permit(:order_status , :production_status)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
       @order = Order.find(params[:id])
       @order_details = @order.order_details
       #@sum = @order.all.sum(:price)

  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details

    if @order.order_status == "入金確認"
       @order_details.each do |order_detail|
        order_detail.production_status =1
        order_detail.save
        end
      end
    redirect_to admin_order_path
  end

  private
  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/views/admin/orders/show.html.erb
<div class="container">
	<div class="row">

 <h5 class=" col-sm-2 col-lg-2.5 m-5 text-center", style="background-color:#e0e0e0">
  注文履歴詳細
 </h5>

<div class="container-fluid">
  <table>
   <tr>
    <th>購入者</th>
    <td><%= link_to admin_customer_path(@order) do %>
        <%= @order.customer.last_name %><%= @order.customer.first_name %>
        <% end %>
    </td>
   </tr>

   <tr>
   <th>注文日</th>
   <td><%= @order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
   </td>
   </tr>

  <tr>
   <th>配送先</th>
   <td><p><%= @order.post_code %><%= @order.address %></p>
      <p><%= @order.name %></p>
  </td>
  </tr>

  <tr>
   <th>支払方法</th>
   <td><%= @order.pay_type_i18n %></td>
  </tr>

  <tr>
   <th>注文ステータス</th>
   <td>
    <%= form_with model:@order, url: admin_order_path, local: true do |f| %>
    <%= f.select :order_status, ["入金待ち", "入金確認","製作中","発送準備中","発送済み"] %>
    <%= f.submit "更新", class: "btn btn-success" %>
    <% end %>
   </td>
  </tr>
  </table>
</div>

<div class="w-75 m-5">
    <table class="table" ,style="align-left">
      <thead class="thead-light">
        <tr>
          <th scope="col" style="width: 30%">商品名</th>
          <th scope="col" style="width: 20%">単価（税込）</th>
          <th class="active">数量</th>
          <th class="active">小計</th>
          <th class="active">製作ステータス</th>
        <tr>
      </thead>
    <% @order_details.each do |order_detail| %>
      <tbody>
        <tr>
          <td class="col-xs-4"><%= order_detail.item.name%></td>
          <td class="col-xs-2">¥ <%= (order_detail.item.price*1.1).floor.to_s(:delimited) %></td>
          <td><%= order_detail.quantity %></td>
          <td class="col-xs-2">¥
           <%= ((order_detail.item.price * order_detail.quantity*1.1).floor).to_s(:delimited) %></td>
          <td>
            <%= form_with model:order_detail, url: admin_order_detail_path(order_detail), local: true do |f| %>
              <%= f.select :production_status, ["着手不可", "製作待ち", "製作中", "製作完了"] %>
              <%= f.submit "更新", class: "btn btn-success" %>
            <% end %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
    </div>

     <div class="mt-5">
       <table>
        <tr>
          <th>商品合計</th>
          <td><%= (@order.billing_amount - @order.postage).to_s(:delimited)%>円</td>
        </tr>
        <tr>
         <th>送料</th>
         <td><span class: "justify-content-end"><% @order.postage = 800 %>
         <%= @order.postage %>円</td>
        </tr>
         <tr>
           <th>請求金額合計</th>
           <td><%= @order.billing_amount %>円</td>
         </tr>
        </table>
    </div>
  </div>