config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  scope module: :public do
    root to: "items#top"
    get '/about' => 'homes#about'

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :confirm, :complete, :create, :index, :show] do
      collection do
        post "confirm"
        get "complete"
      end
    end
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "/customers/mypage" => "customers#show"
    get "/customers/information/edit" => "customers#edit"
    patch "/customers/information" => "customers#update"
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdrawal" => "customers#withdrawal"
    resources :items, only: [:index, :show]
    resources :homes, only: [:top, :about]
  end



  namespace :admin do
    root to: "homes#top"
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update] do
      collection do
        get "search"
      end
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update] do
      collection do
        get "search"
      end
    end
    resources :homes, only: [:top]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "") %>件のエラーが発生したため登録情報は保存されませんでした。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.drawio.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <% if current_page?(admin_customers_path) %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item.active.justify-content-center.align-items-center">
              <%= search_form_for @q, url: search_admin_customers_path do |f| %>
                <%= f.search_field :last_name_or_first_name_or_last_name_kana_or_first_name_kana_cont, placeholder: "姓 or 名 or セイ or メイ" %>
                <%= f.submit '🔍', class: "btn-sm btn-outline-secondary" %>
              <% end %>
              </li>
            </ul>
            <% end %>
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
            <li id="youkoso">ようこそ、<%= current_customer.last_name %>さん！</li>
            </ul>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
               <%= link_to 'マイページ', customers_mypage_path, class: 'btn btn-outline-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧", items_path, class: 'btn btn-outline-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "カート", cart_items_path, class: 'btn btn-outline-dark' %>
            </li>
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-dark' %>
            </li>
            <% elsif admin_signed_in?%>
             <li><%= link_to ' 商品一覧', admin_items_path, class: 'btn btn-outline-dark' %>
             </li>
             <li><%= link_to ' 会員一覧', admin_customers_path, class: 'btn btn-outline-dark' %>
             </li>
             <li><%= link_to ' 注文履歴一覧', admin_root_path, class: 'btn btn-outline-dark'%>
             </li>
             <li><%= link_to ' ジャンル一覧', admin_genres_path, class: 'btn btn-outline-dark' %>
             </li>
             <li><%= link_to ' ログアウト', destroy_admin_session_path, method: :delete, class: 'btn btn-outline-dark' %></li>
            <% else %>
            <li class="nav-item">
              <%= link_to "About", about_path, class: 'btn btn-outline-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧", orders_path, class: 'btn btn-outline-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", customer_session_path, class: 'btn btn-outline-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
       <div class="text-right">
      <%= form_tag search_admin_items_path, method: :get do %>
  <%= text_field_tag :keyword, params[:keyword], placeholder: "キーワードを入力してください" %>
  <%= submit_tag "検索" %>
<% end %>
    </div>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
  </body>
</html>